stages:
  - tf_fmt
  - tf_validate
  - tf_plan
  - tf_apply

# -----------------------
# Shared Terraform config
# -----------------------
.tf_common:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: [""]
  variables:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"
    AWS_REGION: eu-west-2
  before_script:
    - terraform --version

# -----------------------
# Shared OIDC auth block
# -----------------------
.aws_oidc_auth:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - apk add --no-cache aws-cli jq
    - |
      CREDS_JSON="$(aws sts assume-role-with-web-identity \
        --role-arn "${AWS_ROLE_ARN}" \
        --role-session-name "gitlab-${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_IID}" \
        --web-identity-token "${GITLAB_OIDC_TOKEN}" \
        --duration-seconds 3600)"
    - export AWS_ACCESS_KEY_ID="$(echo "$CREDS_JSON" | jq -r '.Credentials.AccessKeyId')"
    - export AWS_SECRET_ACCESS_KEY="$(echo "$CREDS_JSON" | jq -r '.Credentials.SecretAccessKey')"
    - export AWS_SESSION_TOKEN="$(echo "$CREDS_JSON" | jq -r '.Credentials.SessionToken')"
    - aws sts get-caller-identity

# =======================
# PREPROD (develop)
# =======================

tf_fmt_preprod:
  stage: tf_fmt
  extends: .tf_common
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never
  script:
    - cd infra/preprod
    - terraform fmt -check -recursive

tf_validate_preprod:
  stage: tf_validate
  extends: .tf_common
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never
  script:
    - cd infra/preprod
    - terraform init -input=false
    - terraform validate

tf_plan_preprod:
  stage: tf_plan
  extends: [.tf_common, .aws_oidc_auth]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never
  variables:
    AWS_ROLE_ARN: $AWS_ROLE_ARN_PREPROD
  script:
    - cd infra/preprod
    - terraform init -input=false
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - infra/preprod/tfplan
    expire_in: 1 day


tf_apply_preprod:
  stage: tf_apply
  extends: [.tf_common, .aws_oidc_auth]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
    - when: never
  variables:
    AWS_ROLE_ARN: $AWS_ROLE_ARN_PREPROD
  needs: ["tf_plan_preprod"]
  script:
    - cd infra/preprod
    - terraform init -input=false
    - terraform apply -auto-approve tfplan

# =======================
# PROD (tags v*)
# =======================

tf_fmt_prod:
  stage: tf_fmt
  extends: .tf_common
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: on_success
    - when: never
  script:
    - cd infra/prod
    - terraform fmt -check -recursive

tf_validate_prod:
  stage: tf_validate
  extends: .tf_common
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: on_success
    - when: never
  script:
    - cd infra/prod
    - terraform init -input=false
    - terraform validate

tf_plan_prod:
  stage: tf_plan
  extends: [.tf_common, .aws_oidc_auth]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: on_success
    - when: never
  variables:
    AWS_ROLE_ARN: $AWS_ROLE_ARN_PROD
  script:
    - cd infra/prod
    - terraform init -input=false
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - infra/prod/tfplan
    expire_in: 1 day

tf_apply_prod:
  stage: tf_apply
  extends: [.tf_common, .aws_oidc_auth]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: manual
    - when: never
  variables:
    AWS_ROLE_ARN: $AWS_ROLE_ARN_PROD
  needs: ["tf_plan_prod"]
  script:
    - cd infra/prod
    - terraform init -input=false
    - terraform apply -auto-approve tfplan
